using UnityEngine;
using TMPro;

public class BannerBehaviour : MonoBehaviour
{
    [SerializeField] TMP_Text displayBaneer;

    string[] bannerText =
        {
        "PAREM DE MIMIMI",
        "MI MI MI",
        "TERRA É PLANA !!",
        "<color=#0B610B>FORA</color> GLOBALÓIDES",
        "SOMOS <color=#0B610B>GADO</color>",
        "<color=#0B610B>CLOROQUINERS</color>",
        "GOLPE <color=#0B610B>MILITAR</color>",
        "<color=#0B610B>PATRIOTÁRIOS</color>",
        "E DAÍ? NÃO SOU <color=#0B610B>COVEIRO</color>",
        "<color=#0B610B>INTERVENÇÃO</color> PSIQUIÁTRICA JÁ",
        "IDOSOS DE <color=#10CB04>ZAP</color>",
        "TIOZÃO DO <color=#10CB04>ZAP</color>",
        "TIAZONA DO <color=#10CB04>ZAP</color>",
        "RECEBI NO <color=#10CB04>ZAP</color>",
        "SÓ SABEMOS O\n QUE TÁ NO <color=#10CB04>ZAP</color>",
        "SÓ O <color=#0B610B>VIAGRA</color> SALVA",
        "SÓ MAIS <color=#0B610B>72</color> HORAS,\n <color=#002EFF>AGUARDEM</color>!",
        "<color=#002EFF>PENDRIVE</color> DAS ARÁBIAS",
        "AQUI SERVIMOS O SHEIK DO <color=#002EFF>PENDRIVE</color>",
        "SUPREMO É O POVO, NÃO PERA!",
        "NÃO VÃO COMER O MEU CACHORRO",
        "NÃO VAMOS VIRAR <color=#DB261D>JACARÉ</color>",
        "DEITA NA <color=#0B610B>BR</color>  E CHORA",
        "OS CAVALEIROS DO <color=#002EFF>AGUARDEM</color>",
        "BANHEIRO <color=#DB261D>UNISEX</color> SÓ SE FOR <color=#002EFF>QUÍMICO</color>",
        "GOSTAMOS SECRETAMENTE DA <color=#DB261D>ANITTA</color>",
        "GOSTAMOS SECRETAMENTE DA <color=#DB261D>PABLLO</color>",
        "S.O.S. <color=#0B610B>E.T.</color>",
        "S.O.S <color=#0B610B>ALIENÍGENA</color>",
        "INTERVENÇÃO <color=#0B610B>ALIENÍGENA</color>!",
        "A CRISE É ESTÉTICA",
        "FAMÍLIA TRADICIONAL BRASILEIRA E MINHA <color=#002EFF>AMANTE</color>",
        "FAMÍLIA TRADICIONAL BRASILEIRA E MEU <color=#002EFF>AMANTE</color>",
        "NÃO TEMOS VERGONHA NA CARA",
        "NÃO ESTUDAMOS <color=#DB261D>HISTÓRIA</color>",
        "SEM PRESSÃO,\n AQUI É <color=#FFDC00>XANDÃO</color>",
        "TEMOS MEDO DO <color=#FFDC00>XANDÃO</color>",
        "BURROS COM FORÇA <color=#0B610B>(ARMADA)</color>",
        "FEIOS COM FORÇA <color=#0B610B>(ARMADA)</color>",
        "<color=#0B610B>MILÍCIA</color> SUA LINDA",
        "MAMADEIRA DE PIROCA",
        "CANETA BIC NA MÃO\n E OZÔNIO NO TOBA",
        "BROCHAMOS",
        "<color=#0B610B>BROCHAS</color> E <color=#FFDC00>CORNOS</color>",
        "BROCHÁVEL E COMÍVEL",
        "MINHA CASA, MEU HOSPÍCIO",
        "<color=#0B610B>DITADURA</color> JÁ",
        "<color=#0B610B>VOTO IMPRESSO</color>",
        "POXA MINTO",
        "PRO <color=#0B610B>TORTURA</color>",
        "PELO DIREITO DE MATAR",
        "PELO DIREITO DE SER <color=#0B610B>TROUXA</color>",
        "NÃO SOU RICO PORQUE NÃO QUERO",
        "EUA É MELHOR QUE O <color=#002EFF>BRAZIL</color>",
        "TRUMP SALVE O <color=#002EFF>BRAZIL</color>",
        "AMAMOS O <color=#002EFF>BRAZIL</color>",
        "VOLTA <color=#FFDC00>MONARQUIA</color>",
        "<color=#FFDC00>MONARQUIA</color> JÁ!!",
        "<color=#FFDC00>MONARQUIA</color> SUA LINDA",
        "<color=#0B610B>TODO MUNDO</color> TEM\n <color=#10CB04>$107</color> IMÓVEIS",
        "<color=#0B610B>5G</color> NA <color=#2E9AFE>VACINA</color>",
        "CADÊ MEU CHAPÉU DE ALUMÍNIO?",
        "NÃO SOMOS <color=#DB261D>TCHUTCHUCA</color>!",
        "XADREZ 4D",
        "<color=#0B610B>ELE</color> É MUITO <color=#FFDC00>ESTRATEGISTA</color> ,\n <color=#002EFF>AGUARDEM</color>",
        "FILHOTES DA <color=#0B610B>DITADURA</color>",
        "VIÚVAS DA <color=#0B610B>DITADURA</color>",
        "<color=#0B610B>AI-5</color> NO DOS OUTROS\n É MOLE",
        "ESCRAVIDÃO NÃO EXISTIU",
        "NAZISMO É DE ESQUERDA",
        "<color=#0B610B>64</color> FOI UM CONTRAGOLPE <color=#0B610B>MILITAR</color>, SAUDADES",
        "<color=#0B610B>FORA</color> <color=#DB261D>URSAL</color>!!",
        "<color=#0B610B>FORA</color> <color=#DB261D>MARXISMO CULTURAL</color>, MAS O QUE É MESMO?",
        "<color=#DB261D>ESQUERDISTAS</color> SAFADOS!",
        "A <color=#002EFF>DIREITA</color> TRABALHA,\n A <color=#DB261D>ESQUERDA</color> TRANSA",
        "<color=#FFDC00>GOLDEN SHOWER</color>",
        "NÃO EXISTE SEGUNDA-FEIRA NO <color=#DB261D>COMUNISMO</color>",
        "QUEM GOSTA DE <color=#DB261D>HISTÓRIA</color> É <color=#DB261D>ESQUERDISTA</color>",
        "PELA <color=#FFDC00>CONSTITUIÇÃO</color>! <color=#0B610B>DITADURA</color> JÁ!!",
        "O <color=#DB261D>PT</color> ACABOU!!",
        "VOLTA AQUI <color=#002EFF>EMA</color>, TOMA\n SUA <color=#0B610B>CLOROQUINA</color>!",
        "<color=#002EFF>OZÔNIO</color> NO DOS OUTROS É REFRESCO",
        "<color=#0B610B>ANTI-VACINA</color>",
        "<color=#0B610B>FORA</color> <color=#2E9AFE>ZÉ GOTINHA</color>!",
        "<color=#0B610B>FORA</color> <color=#2E9AFE>INSS</color>",
        "<color=#DB261D>LIBERDADE</color> SÓ SE FOR A <color=#002EFF>MINHA</color>",
        "SIGILO DE <color=#10CB04>$100</color> ANOS É POUCO!!",
        "<color=#10CB04>RACHADINHA</color> NÃO É CRIME",
        "<color=#10CB04>BARRA DE OURO</color> PRA MIM, <color=#002EFF>SEM ESCOLA</color> PRA VOCÊ",
        "<color=#10CB04>BARRA DE OURO</color> NÃO É CRIME",
        "<color=#0B610B>GENOCÍDIO</color> NÃO É CRIME",
        "MENTIR TODO DIA NÃO É CRIME",
        "MENTIR TODO DIA FAZ BEM PRA PELE",
        "PINTOU UM CLIMA",
        "<color=#2E9AFE>CRISTÃOS</color> <color=#0B610B>ARMADOS</color>",
        "<color=#2E9AFE>JESUS</color> <color=#0B610B>ARMADO</color>",
        "<color=#2E9AFE>JESUS DISSE:</color> <color=#0B610B>BANDIDO BOM É BANDIDO MORTO</color>",
        "<color=#2E9AFE>JESUS</color> NA <color=#002EFF>GOIABEIRA</color>",
        "<color=#2E9AFE>CRIANÇAS</color> <color=#0B610B>ARMADAS</color>",
        "DEIXA A\n <color=#10CB04>$BOIADA</color> PASSAR",
        "TEM QUE PASSAR\n A <color=#10CB04>$BOIADA</color>",
        "<color=#DB261D>UNIVERSIDADE</color> É BALBÚRDIA",
        "<color=#DB261D>UNIVERSIDADE</color> É PRA POUCOS",
        "<color=#DB261D>UNIVERSIDADE</color> É\n COISA DE RICO",
        "UM <color=#10CB04>DÓLAR</color> POR VACINA",
        "GOLEIRO <color=#002EFF>BRUNO</color> ESTÁ CONOSCO!!",
        "PROPINA NO PNEU",
        "<color=#0B610B>ENGAVETADOR</color> <color=#FFDC00>GERAL</color> DA <color=#002EFF>REPÚBLICA</color>",
        "REPÚBLICA DAS <color=#FFDC00>BANANAS</color>",
        "PICANHA SÓ PRA MIM E MINHA <color=#002EFF>CONGE</color>, <color=#FFDC00>QUÉN</color>",
        "DEUS, PÁTRIA E (<color=#002EFF>A MINHA</color>) FAMÍLIA",
        "SEM PROVAS, SÓ CONVICÇÃO!",
        "O <color=#2E9AFE>SUS</color> NÃO FUNCIONA, OUVI DIZER",
        "CAIXA DE SAPATO CHEIA DE NOTA DE <color=#10CB04>$100</color> NÃO É CRIME",
        "MICHEQUE",
        "<color=FFDC00>BANANINHA</color>",
        "ACREDITAMOS NAS NOTICIAS DO CARLUXO",
        "ACREDITAMOS NA HETEROSSEXUALIDADE\n DO CARLUXO!",
        "AGRO É POP",
        "O <color=#DB261D>BOULOS</color> VAI INVADIR SUA CASA!",
        "O <color=#DB261D>MST</color> VAI INVADIR SUA TERRA!",
        "<color=#0B610B>DITADOR</color> SÓ SE FOR DE <color=#0B610B>DIREITA</color>!!",
        "INTERVENÇÃO <color=#0B610B>MILITAR</color> NÃO É GOLPE",
        "FALA ALGUMA COISA, <color=#002EFF>OLAVO</color>!!",
        "FAZ ALGUMA COISA, <color=#002EFF>OLAVO</color>!!",
        "O <color=#0B610B>AGRO</color> CUIDA DO MEIO AMBIENTE SIM! <color=#0B610B>CONFIA</color>",
    };

    private void Start()
    {
        displayBaneer.text = ChooseBannerText();
    }


    private string ChooseBannerText()
    {
        string randomPhrase = bannerText[Random.Range(0, bannerText.Length)];

        return randomPhrase;
    }

}
