using UnityEngine;
using TMPro;

public class BannerBehaviour : MonoBehaviour
{
    [SerializeField] TMP_Text displayBaneer;

    string[] bannerText =
        {
        "PAREM DE MIMIMI",
        "MI MI MI",
        "TERRA É PLANA !!",
        "FORA GLOBALÓIDES",
        "SOMOS GADO",
        "CLOROQUINERS",
        "GOLPE MILITAR",
        "PATRIOTÁRIOS",
        "E DAÍ? NÃO SOU COVEIRO",
        "INTERVENÇÃO PSIQUIÁTRICA JÁ",
        "IDOSOS DE ZAP",
        "TIOZÃO DO ZAP",
        "TIAZONA DO ZAP",
        "RECEBI NO ZAP",
        "SÓ SABEMOS O QUE TÁ NO ZAP",
        "SÓ O VIAGRA SALVA",
        "SÓ MAIS 72 HORAS, AGUARDEM!",
        "PENDRIVE DAS ARÁBIAS",
        "AQUI SERVIMOS O SHEIK DO PENDRIVE",
        "SUPREMO É O POVO, NÃO PERA!",
        "NÃO VÃO COMER O MEU CACHORRO",
        "NÃO VAMOS VIRAR JACARÉ",
        "DEITA NA BR E CHORA",
        "OS CAVALEIROS DO AGUARDEM",
        "BANHEIRO UNISEX SÓ SE FOR QUÍMICO",
        "GOSTAMOS SECRETAMENTE DA ANITTA",
        "GOSTAMOS SECRETAMENTE DA PABLLO",
        "S.O.S. E.T.",
        "S.O.S ALIENÍGENAS",
        "INTERVENÇÃO ALIENÍGENA!",
        "A CRISE É ESTÉTICA",
        "FAMÍLIA TRADICIONAL BRASILEIRA E MINHA AMANTE",
        "FAMÍLIA TRADICIONAL BRASILEIRA E MEU AMANTE",
        "NÃO TEMOS VERGONHA NA CARA",
        "NÃO ESTUDAMOS HISTÓRIA",
        "SEM PRESSÃO, AQUI É XANDÃO",
        "TEMOS MEDO DO XANDÃO",
        "BURROS COM FORÇA (ARMADA)",
        "FEIOS COM FORÇA (ARMADA)",
        "MILÍCIA SUA LINDA",
        "MAMADEIRA DE PIROCA",
        "CANETA BIC NA MÃO E OZÔNIO NO TOBA",
        "BROCHAMOS",
        "BROCHAS E CORNOS",
        "BROCHÁVEL E COMÍVEL",
        "MINHA CASA, MEU HOSPÍCIO",
        "DITADURA JÁ",
        "VOTO IMPRESSO",
        "POXA MINTO",
        "PRO TORTURA",
        "PELO DIREITO DE MATAR",
        "PELO DIREITO DE SER TROUXA",
        "NÃO SOU RICO PORQUE NÃO QUERO",
        "EUA É MELHOR QUE O BRAZIL",
        "TRUMP SALVE O BRAZIL",
        "AMAMOS O BRAZIL",
        "VOLTA MONARQUIA",
        "MONARQUIA JÁ!!",
        "MONARQUIA SUA LINDA",
        "TODO MUNDO TEM 107 IMÓVEIS",
        "5G NA VACINA",
        "CADÊ MEU CHAPÉU DE ALUMÍNIO?",
        "NÃO SOMOS TCHUTCHUCA!",
        "XADREZ 4D",
        "ELE É MUITO ESTRATEGISTA, AGUARDEM",
        "FILHOTES DA DITADURA",
        "VIÚVAS DA DITADURA",
        "AI-5 NO DOS OUTROS É MOLE",
        "ESCRAVIDÃO NÃO EXISTIU",
        "NAZISMO É DE ESQUERDA",
        "64 FOI UM CONTRAGOLPE MILITAR, SAUDADES",
        "FORA URSAL!!",       
        "FORA MARXISMO CULTURAL, MAS O QUE É MESMO?",
        "ESQUERDISTAS SAFADOS!",
        "A DIREITA TRABALHA, A ESQUERDA TRANSA",
        "GOLDEN SHOWER",
        "NÃO EXISTE SEGUNDA-FEIRA NO COMUNISMO",
        "QUEM GOSTA DE HISTÓRIA É ESQUERDISTA",
        "PELA CONSTITUIÇÃO! DITADURA JÁ!!",
        "O PT ACABOU!!",
        "VOLTA AQUI EMA, TOMA SUA CLOROQUINA!",
        "OZÔNIO NO DOS OUTROS É REFRESCO",
        "ANTI-VACINA",
        "FORA ZÉ GOTINHA!",     
        "FORA INSS",
        "LIBERDADE SÓ SE FOR A MINHA",
        "SIGILO DE 100 ANOS É POUCO!!",
        "RACHADINHA NÃO É CRIME",
        "BARRA DE OURO PRA MIM, SEM ESCOLA PRA VOCÊ",
        "BARRA DE OURO NÃO É CRIME",
        "GENOCÍDIO NÃO É CRIME",
        "MENTIR TODO DIA NÃO É CRIME",
        "MENTIR TODO DIA FAZ BEM PRA PELE",
        "PINTOU UM CLIMA",
        "CRISTÃOS ARMADOS",
        "JESUS ARMADO",
        "JESUS DISSE: BANDIDO BOM É BANDIDO MORTO",
        "JESUS NA GOIABEIRA",
        "CRIANÇAS ARMADAS",
        "DEIXA A BOIADA PASSAR",
        "TEM QUE PASSAR A BOIADA",
        "UNIVERSIDADE É BALBÚRDIA",
        "UNIVERSIDADE É PRA POUCOS",
        "UNIVERSIDADE É COISA DE RICO",
        "UM DÓLAR POR VACINA",
        "GOLEIRO BRUNO ESTÁ CONOSCO!!",
        "PROPINA NO PNEU",
        "ENGAVETADOR GERAL DA REPÚBLICA",
        "REPÚBLICA DAS BANANAS",
        "PICANHA SÓ PRA MIM E MINHA CONGE, QUÉN",
        "DEUS, PÁTRIA E (A MINHA) FAMÍLIA",
        "SEM PROVAS, SÓ CONVICÇÃO!",
        "O SUS NÃO FUNCIONA, OUVI DIZER",
        "CAIXA DE SAPATO CHEIA DE NOTA DE 100 NÃO É CRIME",
        "MICHEQUE",
        "BANANINHA",
        "ACREDITAMOS NAS NOTICIAS DO CARLUXO",
        "ACREDITAMOS NA HETEROSSEXUALIDADE DO CARLUXO!",
        "AGRO É POP",
        "O BOULOS VAI INVADIR SUA CASA!",
        "O MST VAI INVADIR SUA TERRA!",
        "DITADOR SÓ SE FOR DE DIREITA!!",
        "INTERVENÇÃO MILITAR NÃO É GOLPE",
        "FALA ALGUMA COISA, OLAVO!!",
        "FAZ ALGUMA COISA, OLAVO!!",
        "O AGRO CUIDA DO MEIO AMBIENTE SIM!",
    };


    private void Start()
    {
        displayBaneer.text = ChooseBannerText();
    }


    private string ChooseBannerText()
    {
        string randomPhrase = bannerText[Random.Range(0, bannerText.Length)];

        return randomPhrase;
    }

}
